### ISSUE TITLE
Not saving output file

### ISSUE THREAD

**Issue by cBevilaqua** [adminy/cordova-plugin-ffmpeg#10]
I'm using a command to get a snapshot from a video file, it outputs success, but the output file is not saved anywere.

The command I'm using is this:
`const ffcommand = "-i ${videoPath} -ss 00:00:01 -vframes 1 ${snapshotPath}";`
videoPath and snapshotPath are paths built with: cordova.file.externalRootDirectory + filename.ext

Thanks!

**Comment by adminy** [comment]
Make sure you have write permissions to that folder.

The ffmpeg command looks a little plain. provide an output format at least.

**Comment by cBevilaqua** [comment]
Thanks! My problem was just related to the way I was showing the captured screenshot. The img src was not able to read the local file path, so I used: `window.resolveLocalFileSystemURL`
