### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by onlinehk** [adminy/cordova-plugin-ffmpeg#2]
The following build commands failed:
        CompileC /Users/developer/Library/Developer/Xcode/DerivedData/testApp-enlmawcymjixnieklrrmxklvasgl/Build/Intermediates.noindex/ArchiveIntermediates/testApp/IntermediateBuildFilesPath/testApp.build/Debug-iphoneos/testApp.build/Objects-normal/arm64/HWPFFMpeg.o /Users/developer/cordova/test/platforms/ios/testApp/Plugins/com.marin.ffmpeg/FFMpegPlugin/HWPFFMpeg.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

**Comment by onlinehk** [comment]
HWPFFMpeg.m

int returnCode = [MobileFFmpeg getLastReturnCode];
NSString *output = [MobileFFmpeg getLastCommandOutput];

replace to

int returnCode = [MobileFFmpegConfig getLastReturnCode];
NSString *output = [MobileFFmpegConfig getLastCommandOutput];

is ok

**Comment by adminy** [comment]
Done. Next time you're welcome to submit a PR :P
