### ISSUE TITLE
Buld error

### ISSUE THREAD

**Issue by Zapmobilegames** [adminy/cordova-plugin-ffmpeg#4]
I built for Android and I got this issue:

\cordova_app\platforms\android\app\src\main\java\com\marin\plugin\FFMpeg.java:18: error: cannot find symbol
                callbackContext.failure("Error Code: " + returnCode);
                               ^
  symbol:   method failure(String)
  location: variable callbackContext of type CallbackContext
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

I have minsdk 24 and targetsdk 29

**Comment by rhiroshi** [comment]
Made a PR that solves this. 
If you want to patch it yourself while the PR doesnt get accepted, go to the FFMpeg class and change on line 18
`callbackContext.failure("Error Code: " + returnCode);`
to 
`callbackContext.error("Error Code: " + returnCode);`

**Comment by adminy** [comment]
I merged the PR
